---
- name: Configure RHEL 7 with WebLogic 12c domain
  hosts: all
  become: false
  vars_files:
    # User defined variables for infrastructure
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
  roles:
    - role: linux-wls
    - role: linux-jdk
    - role: fmw-software
    # - role: fmw-domain
    # - role: fmw-managed-server
  pre_tasks:

    - name: Passing manditory arguments
      shell: |
        subscription-manager repos --enable ansible-2.8-for-rhel-8-x86_64-rpms
        subscription-manager register --username sunil57.kdp@gmail.com --password Sunil_u2457 --auto-attach --force
        yum install git vim python39 ansible 


   # ==> Fix hosts file. Remove hostname from local loop. A workaround for vagrant
   # adding hostname to local loop
   #- name: fix host file 127.0.0.1 entry
   #  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644


